// GWSpeak.idl : IDL source for GWSpeak.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (GWSpeak.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(A42771AC-03C7-11D3-9F6E-00C095EE683F),
		dual,
		helpstring("ISpeak Interface"),
		pointer_default(unique)
	]
	interface ISpeak : IDispatch
	{
		[id(1), helpstring("method SpeakString")] HRESULT SpeakString(BSTR String);
		[id(2), helpstring("method Silence")] HRESULT Silence();
	};

[
	uuid(A42771A0-03C7-11D3-9F6E-00C095EE683F),
	version(1.0),
	helpstring("GWSpeak 1.0 Type Library")
]
library GWSPEAKLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(A42771AD-03C7-11D3-9F6E-00C095EE683F),
		helpstring("Speak Class")
	]
	coclass Speak
	{
		[default] interface ISpeak;
	};
};
