/*
 * Copyright (c) 2001-2007, TIBCO Software Inc.
 * Use, modification, and distribution subject to terms of license.
 */
jsx3.require("jsx3.gui.Block");jsx3.Class.defineClass("jsx3.gui.Window",jsx3.app.Model,null,function(a,n){var
ub={O:"_JSXROOT",k:"pclose",h:"close",c:"screenLeft",H:'<span id="',p:"directories=no,location=no,menubar=no,status=yes,personalbar=no,titlebar=yes,toolbar=no,width=",P:"100%",q:",",G:"type",v:"scrollbars=",I:'"></span>',i:"focus",A:"head",a:"jsx3.gui.window.html",F:"rel",u:"no",t:"yes",j:"resize",N:"onParentUnload",s:"resizable=",S:" ",z:"body",d:"screenTop",o:/\./g,D:"href",R:"@Solid Light",K:"onFocus ",w:"_jsxwindow",r:"height=",C:"stylesheet",B:"link",l:"",g:"open",Q:"jsxbgcolor",L:"onBeforeUnload ",b:"jsx3.gui.window.xhtml",M:"onResize ",m:"gui.win.op",f:"screenY",J:"jsx3",y:"onLoad ",n:".xhtml",x:"gui.win.cl",E:"id",e:"screenX"};var
Y=jsx3.Exception;var
ca=jsx3.util.Logger;var
Ra=ca.getLogger(a.jsxclass.getName());a.jZ=new
jsx3.net.URI(ub.a);a.KG=new
jsx3.net.URI(ub.b);if(jsx3.CLASS_LOADER.IE){a.CI=ub.c;a.xO=ub.d;}else{a.CI=ub.e;a.xO=ub.f;}a.DID_OPEN=ub.g;a.WILL_CLOSE=ub.h;a.DID_FOCUS=ub.i;a.DID_RESIZE=ub.j;a.PARENT_DID_CLOSE=ub.k;n.jsxwidth=400;n.jsxheight=300;n.jsxresizable=0;n.jsxscrollable=0;n.jsxdependent=1;n.jsxtitle=ub.l;n._jsxwindow=null;n._jsxpB=null;n.init=function(b){this.jsxsuper(b);};n.open=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){throw new
Y(jsx3._msg(ub.m,this));}else{var
R=jsx3.util.strEndsWith(jsx3.app.Browser.getLocation().getPath().toLowerCase(),ub.n)?a.KG:a.jZ;var
tb=window.open(R.toString(),this.getId().replace(ub.o,ub.l),ub.p+this.getWidth()+ub.q+ub.r+this.getHeight()+ub.q+ub.s+(this.isResizable()?ub.t:ub.u)+ub.q+ub.v+(this.isScrollable()?ub.t:ub.u));if(tb!=null){tb[ub.w]=this;this._jsxwindow=tb;this._jsxpB=window;return true;}else return false;}};n.close=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){this._jsxwindow.close();return true;}else throw new
Y(jsx3._msg(ub.x,this));};n.focus=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){this._jsxwindow.focus();}else throw new
Y(jsx3._msg(ub.x,this));};n.isOpen=function(){return this._jsxwindow!=null&&!this._jsxwindow.closed;};n.isParentOpen=function(){return this._jsxpB!=null&&!this._jsxpB.closed;};n.moveTo=function(m,q){if(this._jsxwindow!=null&&!this._jsxwindow.closed){if(this._jsxpB!=null&&!this._jsxpB.closed)this._jsxwindow.moveBy(m-this._jsxwindow[a.CI]+this._jsxpB[a.CI],q-this._jsxwindow[a.xO]+this._jsxpB[a.xO]);else this._jsxwindow.moveBy(m-this._jsxwindow[a.CI],q-this._jsxwindow[a.xO]);}else throw new
Y(jsx3._msg(ub.x,this));};n.constrainToScreen=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){var
ya=this._jsxwindow;if(ya[a.CI]<0||ya[a.CI]>window.screen.width||ya[a.xO]<0||ya[a.xO]>window.screen.height)ya.moveTo(0,0);}};n.getOffsetLeft=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){if(this._jsxpB!=null&&!this._jsxpB.closed)return this._jsxwindow[a.CI]-this._jsxpB[a.CI];else return this._jsxwindow[a.CI];}else throw new
Y(jsx3._msg(ub.x,this));};n.getOffsetTop=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){if(this._jsxpB!=null&&!this._jsxpB.closed)return this._jsxwindow[a.xO]-this._jsxpB[a.xO];else return this._jsxwindow[a.xO];}else throw new
Y(jsx3._msg(ub.x,this));};n.onLoad=function(b){if(Ra.isLoggable(5))Ra.debug(ub.y+this);var
Hb=b.document;var
Fa=b.opener;var
Xa=Hb.getElementsByTagName(ub.z)[0];var
Ja=Hb.getElementsByTagName(ub.A)[0];var
S=this.getServer().getRootDocument();var
Z=S.getElementsByTagName(ub.B);for(var
U=0;U<Z.length;U++){var
_=Z[U];if(_.rel==ub.C){var
ra=_.getAttribute(ub.D);var
B=Hb.createElement(ub.B);B.setAttribute(ub.E,_.getAttribute(ub.E));B.setAttribute(ub.D,ra);B.setAttribute(ub.F,_.getAttribute(ub.F));B.setAttribute(ub.G,_.getAttribute(ub.G));Ja.appendChild(B);}}Xa.innerHTML=ub.H+this.getRootBlock().getId()+ub.I;this.getRootBlock().repaint();b[ub.J]=Fa.jsx3;this._jsxwindow=b;this._jsxpB=Fa;this.setTitle(this.getTitle());this.publish({subject:ub.g});};n.onFocus=function(){if(Ra.isLoggable(5))Ra.debug(ub.K+this);this.publish({subject:ub.i});};n.onBeforeUnload=function(){if(Ra.isLoggable(5))Ra.debug(ub.L+this);if(this._jsxwindow!=null){jsx3.gui.Event._deregisterWindow(this._jsxwindow);for(var _a in this._jsxwindow)try{this._jsxwindow[_a]=null;}catch(Kb){}}if(this._jsxpB!=null&&!this._jsxpB.closed)this._jsxpB.focus();this._jsxwindow=null;this._jsxpB=null;this.publish({subject:ub.h});};n.onResize=function(){if(Ra.isLoggable(6))Ra.trace(ub.M+this);this.jsxwidth=this._jsxwindow.document.body.clientWidth;this.jsxheight=this._jsxwindow.document.body.clientHeight;if(this._jsxD3!=null)this._jsxwindow.clearTimeout(this._jsxD3);var
ra=this;this._jsxD3=this._jsxwindow.setTimeout(function(){ra._jsxD3=null;jsx3.gui.Painted.Queue.enableChunking(false);ra.getRootBlock().af({parentwidth:ra.getWidth(),parentheight:ra.getHeight()},true);jsx3.gui.Painted.Queue.enableChunking(true);},250);this.publish({subject:ub.j});};n.onParentUnload=function(){if(Ra.isLoggable(5))Ra.debug(ub.N);this.publish({subject:a.DID_PARENT_CLOSE});};n.getRootBlock=function(){var
ya=this.getChild(0);if(ya==null){ya=new
jsx3.gui.Block(this.getName()+ub.O,0,0,ub.P,ub.P,ub.l);ya.setDynamicProperty(ub.Q,ub.R);ya.setRelativePosition(0);ya.setOverflow(2);ya.setIndex(0);this.setChild(ya);}return ya;};n.getWindow=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed)return this._jsxwindow;return null;};n.getParentWindow=function(){if(this._jsxpB!=null&&!this._jsxpB.closed)return this._jsxpB;return null;};n.getDocument=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed)return this._jsxwindow.document;return null;};n.uf=function(){return {parentwidth:this.getWidth(),parentheight:this.getHeight()};};n.repaint=function(){return this.getRootBlock().repaint();};n.getWidth=function(){return this.jsxwidth;};n.setWidth=function(p){if(this._jsxwindow!=null&&!this._jsxwindow.closed)this._jsxwindow.resizeBy(p-this.jsxwidth,0);this.jsxwidth=p;};n.getHeight=function(){return this.jsxheight;};n.setHeight=function(m){if(this._jsxwindow!=null&&!this._jsxwindow.closed)this._jsxwindow.resizeBy(0,m-this.jsxheight);this.jsxheight=m;};n.isResizable=function(){return this.jsxresizable;};n.setResizable=function(j){this.jsxresizable=jsx3.Boolean.valueOf(j);};n.isScrollable=function(){return this.jsxscrollable;};n.setScrollable=function(o){this.jsxscrollable=jsx3.Boolean.valueOf(o);};n.isDependent=function(){return this.jsxdependent;};n.setDependent=function(b){this.jsxdependent=jsx3.Boolean.valueOf(b);};n.getTitle=function(){return this.jsxtitle;};n.setTitle=function(c){this.jsxtitle=c;if(this._jsxwindow!=null&&!this._jsxwindow.closed)this._jsxwindow.document.title=c;};n.toString=function(c){return this.jsxsuper()+ub.S+this.getName();};});
