name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.6
        uses: actions/setup-java@v1
        with:
          java-version: 1.6
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml package
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy to Maven OSS
        run: mvn deploy:deploy-file -DgeneratePom=false -DrepositoryId=ossrh -Durl=https://oss.sonatype.org/content/repositories/snapshots/ -Dfile=dist/lib/dwr-3.0.3-SNAPSHOT.jar -DpomFile=pom.xml -Dpackaging=jar -Djavadoc=dist/lib/dwr-3.0.3-SNAPSHOT-javadoc.jar -Dsources=dist/lib/dwr-3.0.3-SNAPSHOT-sources.jar -Dfiles=dist/lib/dwr-3.0.3-SNAPSHOT-jdk14.jar -Dclassifiers=jdk14 -Dtypes=jar,jar
