name: Development CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.6
        uses: actions/setup-java@v1
        with:
          java-version: 1.6
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml package
      - name: Read DWR major/version
        id: read_dwr_major
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'core/impl/main/java/dwr-version.properties'
          property: 'major'
      - name: Read DWR minor/version
        id: read_dwr_minor
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'core/impl/main/java/dwr-version.properties'
          property: 'minor'
      - name: Read DWR revision/version
        id: read_dwr_revision
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'core/impl/main/java/dwr-version.properties'
          property: 'revision'
      - name: Read DWR title
        id: read_dwr_title
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'core/impl/main/java/dwr-version.properties'
          property: 'title'
      - name: Set up Maven OSS Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to Maven OSS
        if: ${{steps.read_dwr_title.outputs.value}} == "SNAPSHOT"
        run: mvn deploy:deploy-file -DgeneratePom=false -DrepositoryId=ossrh -Durl=https://oss.sonatype.org/content/repositories/snapshots/ -Dfile=dist/lib/dwr-${{env.DWR_VERSION}}.jar -Dtype=jar -DartifactId=dwr -DpomFile=target/pom.xml -Dpackaging=jar -Djavadoc=dist/lib/dwr-${{env.DWR_VERSION}}-javadoc.jar -Dsources=dist/lib/dwr-${{env.DWR_VERSION}}-sources.jar -Dfiles=dist/lib/dwr-${{env.DWR_VERSION}}-jdk14.jar -Dclassifiers=jdk14 -Dtypes=jar
        env:
          MAVEN_USERNAME: ${{secrets.MAVEN_USERNAME}}
          MAVEN_PASSWORD: ${{secrets.MAVEN_PASSWORD}}
          DWR_VERSION: ${{steps.read_dwr_major.outputs.value}}.${{steps.read_dwr_minor.outputs.value}}.${{steps.read_dwr_revision.outputs.value}}-${{steps.read_dwr_title.outputs.value}}
          
